//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenHouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indication
    {
        public long Date { get; set; }
        public long Sensor_type { get; set; }
        public Nullable<decimal> Temperature { get; set; }
        public Nullable<decimal> Humidity { get; set; }
        public long Sensor_Id { get; set; }
    
        public virtual Sensor_type Sensor_type1 { get; set; }
    }
}
